### ISSUE TITLE
CMYK colors are not correct

### ISSUE THREAD

**Issue by doitliketyler** [elchininet/ColorTranslator#1]
Hey there. I'm trying to convert a hex to cmyk and the cmyk that is returned is not correct. For example #41835C converts to cmyk(50,0,30,49) which are 2 different colors. Any ideas has to what might be happening? If you test on your side do you get the same value? Thanks in advance.

**Comment by elchininet** [comment]
Hi, I will check it. I'll let you know when it is solved. Regards!
