### ISSUE TITLE
Typescript definitions don't work

### ISSUE THREAD

**Issue by anselanza** [elchininet/ColorTranslator#134]
Installed the package (I'm using a ViteJS + React + TypeScript project) and immediately VSCode complains about the type definitions:

```
Could not find a declaration file for module 'colortranslator'. '/Users/stephen/repos/zara-douyin/live-gradients/node_modules/colortranslator/esm/index.js' implicitly has an 'any' type.
  There are types at '/Users/stephen/repos/zara-douyin/live-gradients/node_modules/colortranslator/index.d.ts', but this result could not be resolved when respecting package.json "exports". The 'colortranslator' library may need to update its package.json or typings.ts(7016)
```

**Comment by elchininet** [comment]
Hi @anselanza,
It should be easy to solve, I‘ll publish a version and I‘ll let you know.
Regards

**Comment by elchininet** [comment]
Hi @anselanza,
Please, try with the [version 3.0.2](https://www.npmjs.com/package/colortranslator/v/3.0.2) of the library and report back.
Regards
