### ISSUE TITLE
Add readonly `name` property

### ISSUE THREAD

**Issue by uncenter** [elchininet/ColorTranslator#137]
The `name` property could return either a string (the name) or `undefined` if there is no associated color name with the color.

```js
const color = new ColorTranslator('#FF00FF');
console.log(color.name) // 'fuchsia'
const otherColor = new ColorTranslator('#846C5B');
console.log(color.name) // undefined
```

CSS color keywords are already valid inputs but they are the only input that is not available as a property on the class.

**Comment by elchininet** [comment]
Hi @uncenter,

Your request would not be possible, there are two issues with that. First one, you already mentioned it, not all colors have their named counterpart, so `undefined` should be returned in their place. The second one is that a single color could have more than one named representation, so in these cases it would be required to return an array. These two issues clash with some principles of the API:

1. An output is always a valid input
2. As an output is always a valid input, outputs could always be used to create another instance or to perform another conversion

So, for your use case, you can use the library to convert any input to its `HEX` representation, and later try to search that color in your own `color` => `named-color` dictionary, then you can return `undefined` if it is not in the dictionary, or you can decide if you want to return a ramdom named-color in case that there is more than one or return an array.

* gray / grey = `#808080`
* fuchsia / magenta = `#FF00FF`
* aqua / cyan = `#00FFFF`
* darkgray / darkgrey = `#A9A9A9 `
* darkslategray / darkslategrey = `#2F4F4F`
* dimgray / dimgrey = `#696969`
* lightgray / lightgrey = `#D3D3D3`
* lightslategray / lightslategrey = `#778899`
* slategray / slategrey = `#708090`

**Comment by uncenter** [comment]
Totally understand. Didn't know that having every output as a valid input was a requirement! I was just curious if there was any interest since it seems pretty easy to implement.

Could this work?
```js
const color = new ColorTranslator('#FF00FF');
console.log(color.name) // ['fuchsia']
const otherColor = new ColorTranslator('#846C5B');
console.log(color.name) // []
```

**Comment by elchininet** [comment]
>Could this work?

No, it will not work, because `[]` or `['fuchsia']` are not valid inputs, and in any case it should be `['fuchsia', 'magenta']` because both are the valid named-colors for `#FF00FF`.

**Comment by elchininet** [comment]
By the way @uncenter, if you don‘t want to write your own implementation, you can use [color-namer](https://github.com/colorjs/color-namer) and get your desired result in [this way](https://runkit.com/embed/cc0xtyqpdr90). 

[The same example with an invalid color](https://runkit.com/embed/pq56eko2jd0c).

**Comment by uncenter** [comment]
Hmm. It does seem odd to me that I should have to install a completely different package just to access information already in this one.

**Comment by uncenter** [comment]
> By the way @uncenter, if you don‘t want to write your own implementation, you can use [color-namer](https://github.com/colorjs/color-namer) and get your desired result in [this way](https://runkit.com/embed/cc0xtyqpdr90).
> 
> [The same example with an invalid color](https://runkit.com/embed/pq56eko2jd0c).

Thanks. I already made my own package for this but I just thought it could be a neat addition :)
