### ISSUE TITLE
Convert to L*a*b* format

### ISSUE THREAD

**Issue by uncenter** [elchininet/ColorTranslator#140]
I'm interested in being able to convert colors to and from L\*a\*b\* with ColorTranslator. 

References
- https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/lab
- https://en.wikipedia.org/wiki/CIELAB_color_space.

Existing implementations:
- https://github.com/antimatter15/rgb-lab

**Comment by elchininet** [comment]
Hi @uncenter,
That‘s been in my backlog for a while. It is time to take a look at it it seems :)
I‘ll work on it when I get some time. Letting this issue open until then.
Regards

**Comment by elchininet** [comment]
Hi @uncenter,
The feature is ready to be shipped in a new version. Take a look at [the new dfocumentation](https://github.com/elchininet/ColorTranslator/tree/add_support_for_Lab_color) and lert me know if everything is clear for you. I‘ll merge the changes and release a new version when you have checked it.
Regards

**Comment by uncenter** [comment]
Wow thank you so much for the quick turnaround! Give me a day to review all the changes and I'll let you know :)
Is there any way I can test it as well?

**Comment by elchininet** [comment]
>Is there any way I can test it as well?

Of course, just fork the repo, checkout that branch and execute `yarn demo` to open [the same demo page but in your local](https://elchininet.github.io/ColorTranslator/). I have created an example for colors equivalences that ca help you to play around with it:

<img width="1202" alt="image" src="https://github.com/elchininet/ColorTranslator/assets/3728220/78e1edd8-854d-4773-9d35-e234fe4ad0a8">

**Comment by uncenter** [comment]
Oh yeah 😅 I'll give that a go!

**Comment by elchininet** [comment]
Hi @uncenter,
[Version 4.0.0 has been released](https://www.npmjs.com/package/colortranslator/v/4.0.0).
Regards
