### ISSUE TITLE
Integrity check failed

### ISSUE THREAD

**Issue by tomkys144** [elchininet/ColorTranslator#60]
Hi,
when trying to install ColorTranslator (either by using `yarn` or `npn` error saying that integrity check failed occures.

```bash
yarn add colortranslator
yarn add v1.22.15
[1/4] Resolving packages...
[2/4] Fetching packages...
error https://registry.yarnpkg.com/colortranslator/-/colortranslator-1.9.0.tgz: Integrity check failed for "colortranslator" (computed integrity doesn't match our records, got "sha512-6X1ilN5STXAyRosO3bEUq40oTTOJzzJE6xynkGAHKqOEXFJ6FZWx3SnE6BDBowoF5OOynUgXs8vnkC1OzVA2GQ== sha1-PTobSprMGPS/PdDzqOFRsq0xNaY=")
```

**Comment by elchininet** [comment]
Hi @tomkys144, does it happen to you only with the last version?
What happens if you try to install the previous version?

```
npm install colortranslator@1.8.0
```

**Comment by tomkys144** [comment]
Hi, I tried 1.9.0, 1.8.0 and 1.7.1 and only one failing is 1.9.0... Again same behavior with both npm and yarn

**Comment by elchininet** [comment]
Hi @tomkys144, I‘ve published a patch version just changing the CHANGELOG. Try to install the latest package (1.9.1) and let me know if you have any issue.

**Comment by elchininet** [comment]
Well, I don‘t know what happened there but good to know that the latest one is working properly for you :)
Regards and thanks for reporting!
