### ISSUE TITLE
0BSD-licensed code from Microsoft?

### ISSUE THREAD

**Issue by jeremykohn** [elchininet/ColorTranslator#62]
Although this repo's license is specified as Apache 2.0, the compressed file [colortranslator.js](https://github.com/elchininet/ColorTranslator/blob/master/dist/web/colortranslator.js) apparently includes a 0BSD License block that starts with "Copyright (c) Microsoft Corporation."

I'm not sure why that is. Did any code here come from Microsoft? And if so, what's the license of that code?

**Comment by elchininet** [comment]
Hi @jeremykohn,

The library is written in `TypeScript`, which uses [tslib](https://github.com/Microsoft/tslib) for the helper functions. `tslib` uses a [BSD Zero Clause License](https://github.com/microsoft/tslib/blob/main/LICENSE.txt):

>The BSD Zero Clause license goes further than the BSD 2-Clause license to allow you unlimited freedom with the software without requirements to include the copyright notice, license text, or disclaimer in either source or binary forms.

This licence doesn‘t conflict with [Apache-2.0 License](https://github.com/elchininet/ColorTranslator/blob/master/LICENSE.md), so you don‘t need to worry about it. Anyway, it will be good to remove this licence from the bundle to avoid any confusion in the future. I‘ll let this issue open and I‘ll close it when a patch version without this comment is released.

Regards.

**Comment by elchininet** [comment]
Hi @jeremykohn,
[version 1.9.2](https://www.npmjs.com/package/colortranslator/v/1.9.2) doesn‘t have that license text in the bundle.
Regards.
