### ISSUE TITLE
NOT_ACCEPTED_STRING_INPUT when there's no leading zero in the alpha value in an rgba string

### ISSUE THREAD

**Issue by atkdef** [elchininet/ColorTranslator#80]
Hi, 

As the title states, for rgba string input, when the alpha value has the format "\\.\d+", it reports 

> Uncaught Error: The provided string color doesn't have a correct format

Actually, this is not the only scenario this error will be reported. Multiple leading zeros will also cause this error, but in my opinion this edge case is rare and more likely to be an human error. On the other hand, it's quite common to omit the leading zero in practise.

**Comment by elchininet** [comment]
Hi @atkdef,
Thanks for reporting. I‘ll let you know when it is fixed.
Regards.

**Comment by elchininet** [comment]
Hi @atkdef,
[Version 1.9.4](https://www.npmjs.com/package/colortranslator/v/1.9.4) of the package [solves this issue](https://runkit.com/embed/zajhqvbucm85).
Regards and thanks again for reporting.
