### ISSUE TITLE
Probable bug in RYB to RGB calculation

### ISSUE THREAD

**Issue by jagracar** [elchininet/ColorTranslator#87]
Hi! I came to this repo from your reply to this question in stackoverflow:
https://stackoverflow.com/questions/4255973/calculation-of-a-mixed-color-in-rgb

I'm quite sure the paper you mention has an error in the calculation of gRGB. Instead of using 

`const gRGB = yRYB + 2 * minYB;
`

one should use

`const gRGB = yRYB + minYB;
`

Otherwise transforming cyan from RGB to RYB and then back to RGB produces a different color.

Could you have a check if i'm right? Thanks!

**Comment by elchininet** [comment]
Hi @jagracar,
Sure I can check what are the results. I‘ll let you know.
Regards

**Comment by elchininet** [comment]
Hi @jagracar,
I have tested and indeed, with cyan color it was failing and with your fix it gets solved. The demo and the tests are not affected so I applied your fix straight away. It has been shipped in the [version 1.10.1 of the package](https://www.npmjs.com/package/colortranslator/v/1.10.1).
Regards and thanks.

**Comment by jagracar** [comment]
Thanks!
