### ISSUE TITLE
HEXA doesn't match when translated to RGBA, and then back to HEXA

### ISSUE THREAD

**Issue by jeronimoek** [elchininet/ColorTranslator#98]
Hi! As you may recall, a few days ago I opened an issue regarding that when I gave as input an HEXA and then requested the HEXA value, it wouldn't match. That got fixed. But the problem is different now;
Due to how the VSCode API works, once a user chooses to translate a color to another format, all the old values are gone, and now I have to parse the color again with the new format (loosing the old values). Because of this, when I translate a HEXA value to a RGBA format, and then back to HEXA, the value has changed.

I quickly tested it to see if it was just the value that I was testing it on, and found that this happens with 155 HEXA values (considering just two digits, nearly a 60% percent of the possible HEX Alpha values). A quick way to solve this would be bringing up the MIN_DECIMALS value to 3, using that value, there is not a single case where the alpha value changes when going (HEXA string -> RGBA string -> HEXA string).

**Quick test:**
```
const different = [];
for (let i = 0; i < 16 ** 2; i++) {
  const colorString = "#" + i.toString(16).padStart(2, "0").repeat(4);
  const colorHex = new ColorTranslator(colorString);
  const colorRgb = new ColorTranslator(colorHex.RGBA);
  if (colorRgb.HEXA.toUpperCase() !== colorString.toUpperCase()) {
    console.log(colorRgb.HEXA.toUpperCase(), colorString.toUpperCase());
    different.push(colorString.slice(-2) + "-" + colorRgb.HEXA.slice(-2));
  }
}
console.log(different, different.length);
```

Testing the same for the other formats, I found that with the current code, RGBA and HSLA translation give 155 different HEXA back, HEXA (two conversions of the same) has no different, and CMYKA gives 156*.
When we bring up "MIN_DECIMALS" to 3, RGBA and HEXA has 0 different, HSLA still has 155, and CMYKA now has 155* too.

\* : for the CMYKA I excluded the HEXA "#00000000" since when translated to CMYKA gives an invalid output (I will refer to that in another issue)

**Comment by jeronimoek** [comment]
As a proposal, I was thinking that given that it is expected for the user to receive max 2 decimal digits, one option might be to add a method for the end user to set how many decimal digits they want

**Comment by elchininet** [comment]
Hi @jeronimoek,
I think that this would require to release a major version with more options for the static methods and a new optional parameter in the instances of the class but I‘ll try to find if there is a way that could be retro compatible with the current version.
Regards.

**Comment by jeronimoek** [comment]
thanks, I look forward to it!
